/* import { QuestionSet } from "src/app/core/models/QuestionSet"; */


export const GRAMMAR_QUESTIONS: string = `come;venir;2;verb;
go;ir;2;verb;
eat;comer;2;verb;
drink;beber;2;verb;
work;trabajar;2;verb;
study;estudiar;2;verb;
make;hacer / crear;2;verb;
do;hacer;2;verb;
have;tener;2;verb;
be;ser / estar;2;verb;
can;poder;2;modal_verb;
must;deber;2;modal_verb;
should;debería;2;modal_verb;
will;futuro / voluntad;2;modal_verb;
going to;ir a (futuro);2;future_structure;
come on;vamos / anímate;2;phrasal_verb;
get up;levantarse;2;phrasal_verb;
look for;buscar;2;phrasal_verb;
turn on;encender;2;phrasal_verb;
turn off;apagar;2;phrasal_verb;
give up;rendirse;2;phrasal_verb;
have got;tener (posesión);2;structure_have_got;
I;yo;2;pronoun_subject;
you;tú / usted;2;pronoun_subject;
he;él;2;pronoun_subject;
she;ella;2;pronoun_subject;
it;eso / ello;2;pronoun_subject;
we;nosotros;2;pronoun_subject;
they;ellos;2;pronoun_subject;
me;me / mí;2;pronoun_object;
him;lo / le;2;pronoun_object;
her;la / le;2;pronoun_object;
my;mi;2;possessive_adjective;
your;tu / su;2;possessive_adjective;
his;su (de él);2;possessive_adjective;
her;su (de ella);2;possessive_adjective;
mine;mío;2;possessive_pronoun;
yours;tuyo;2;possessive_pronoun;
this;este / esta;2;demonstrative;
that;ese / esa;2;aquel;demonstrative
these;estos / estas;2;demonstrative;
those;esos / esas;2;aquellos;demonstrative
big;grande;2;adjective;
small;pequeño;2;adjective;
good;bueno;2;adjective;
bad;malo;2;adjective;
easy;fácil;2;adjective;
difficult;difícil;2;adjective;
happy;feliz;2;adjective;
tired;cansado;2;adjective;
bigger;más grande;2;comparative_adjective;
smaller;más pequeño;2;comparative_adjective;
better;mejor;2;comparative_adjective;
worse;peor;2;comparative_adjective;
the biggest;el más grande;2;superlative_adjective;
the best;el mejor;2;superlative_adjective;
very;muy;2;adverb_intensity;
too;demasiado;2;adverb_intensity;
enough;suficiente;2;adverb_intensity;
always;siempre;2;adverb_frequency;
usually;usualmente;2;adverb_frequency;
sometimes;a veces;2;adverb_frequency;
never;nunca;2;adverb_frequency;
now;ahora;2;adverb_time;
today;hoy;2;adverb_time;
tomorrow;mañana;2;adverb_time;
here;aquí;2;adverb_place;
there;allí;2;adverb_place;
in;en;2;preposition;
on;sobre / en;2;preposition;
at;en (lugar/tiempo);2;preposition;
to;a / hacia;2;preposition;
from;de / desde;2;preposition;
with;con;2;preposition;
without;sin;2;preposition;
for;para / por;2;preposition;
about;sobre;2;preposition;
and;y;2;conjunction;
but;pero;2;conjunction;
or;o;2;conjunction;
because;porque;2;conjunction;
if;si;2;conjunction;
some;algunos;2;quantifier;
any;algún / ninguno;2;quantifier;
many;muchos;2;quantifier;
much;mucho;2;quantifier;
few;pocos;2;quantifier;
little;poco;2;quantifier;
how much;cuánto;2;question_structure;
how many;cuántos;2;question_structure;
what;qué;2;wh_word;
where;dónde;2;wh_word;
when;cuándo;2;wh_word;
why;por qué;2;wh_word;
how;cómo;2;wh_word;
yes;sí;2;basic_answer;
no;no;2;basic_answer;
ok;vale / bien;2;common_expression;
thank you;gracias;2;common_expression;
you’re welcome;con gusto;2;common_expression;
what’s up;qué tal;2;informal_expression;
see you;nos vemos;2;common_expression;
gonna;ir a (informal);2;informal_future;
wanna;querer (informal);2;informal_structure;
gotta;tener que (informal);2;informal_structure;
start;empezar;2;verb;
finish;terminar;2;verb;
open;abrir;2;verb;
close;cerrar;2;verb;
buy;comprar;2;verb;
sell;vender;2;verb;
pay;pagar;2;verb;
need;necesitar;2;verb;
want;querer;2;verb;
like;gustar / agradar;2;verb;
know;saber / conocer;2;verb;
think;pensar;2;verb;
feel;sentir;2;verb;
find;encontrar;2;verb;
lose;perder;2;verb;
bring;traer;2;verb;
take;tomar / llevar;2;verb;
put;poner;2;verb;
keep;mantener;2;verb;
leave;salir / dejar;2;verb;
arrive;llegar;2;verb;
wait;esperar;2;verb;
help;ayudar;2;verb;
try;intentar;2;verb;
call;llamar;2;verb;
ask;preguntar;2;verb;
answer;responder;2;verb;
say;decir;2;verb;
tell;contar / decir;2;verb;
speak;hablar;2;verb;
talk;conversar;2;verb;
listen;escuchar;2;verb;
hear;oír;2;verb;
watch;mirar;2;verb;
see;ver;2;verb;
run;correr;2;verb;
walk;caminar;2;verb;
drive;conducir;2;verb;
travel;viajar;2;verb;
stay;quedarse;2;verb;
live;vivir;2;verb;
move;mover / mudarse;2;verb;
stop;detener;2;verb;
continue;continuar;2;verb;
change;cambiar;2;verb;
use;usar;2;verb;
clean;limpiar;2;verb;
cook;cocinar;2;verb;
eat out;comer fuera;2;phrasal_verb;
wake up;despertarse;2;phrasal_verb;
sit down;sentarse;2;phrasal_verb;
stand up;ponerse de pie;2;phrasal_verb;
go on;continuar;2;phrasal_verb;
find out;averiguar;2;phrasal_verb;
take off;quitar / despegar;2;phrasal_verb;
put on;ponerse (ropa);2;phrasal_verb;
pick up;recoger;2;phrasal_verb;
drop off;dejar;2;phrasal_verb;
get in;entrar;2;phrasal_verb;
get out;salir;2;phrasal_verb;
get back;regresar;2;phrasal_verb;
at home;en casa;2;common_expression;
right now;ahora mismo;2;time_expression;
later;más tarde;2;time_expression;
early;temprano;2;time_expression;
late;tarde;2;time_expression;
every day;cada día;2;time_expression;
last night;anoche;2;time_expression;
next week;la próxima semana;2;time_expression;
a lot;mucho / mucho de;2;quantity_expression;
a little;un poco;2;quantity_expression;
a few;unos pocos;2;quantity_expression;
one more;uno más;2;quantity_expression;
too much;demasiado;2;quantity_expression;
too many;demasiados;2;quantity_expression;
there is;hay (singular);2;existential_structure;
there are;hay (plural);2;existential_structure;
used to;solía / acostumbraba;2;past_structure;
be able to;ser capaz de;2;ability_structure;
have to;tener que;2;obligation_structure;
don’t have to;no tener que;2;obligation_structure;
need to;necesitar;2;obligation_structure;
want to;querer;2;verb_structure;
like to;gustar;2;verb_structure;
good morning;buenos días;2;greeting;
good afternoon;buenas tardes;2;greeting;
good evening;buenas noches;2;greeting;
good night;buenas noches;2;farewell;
excuse me;disculpe;2;polite_expression;
sorry;lo siento;2;polite_expression;
please;por favor;2;polite_expression;
no problem;no hay problema;2;common_expression;
of course;por supuesto;2;common_expression;
maybe;tal vez;2;adverb;
probably;probablemente;2;adverb;
really;realmente;2;adverb;
actually;en realidad;2;adverb;
already;ya;2;adverb_time;
still;todavía;2;a dverb_time;
yet;aún / todavía;2;adverb_time;
almost;casi;2;adverb;
only;solo;2;adverb;
same;mismo;2;adjective;
different;diferente;2;adjective;
new;nuevo;2;adjective;
old;viejo;2;adjective;
young;joven;2;adjective;
long;largo;2;adjective;
short;corto;2;adjective;
fast;rápido;2;adjective;
slow;lento;2;adjective;
cheap;barato;2;adjective;
expensive;caro;2;adjective;
full;lleno;2;adjective;
empty;vacío;2;adjective;
ready;listo;2;adjective;
busy;ocupado;2;adjective;
free;libre;2;adjective;
sure;seguro;2;adjective;
true;VERDADERO;2;adjective;
false;FALSO;2;adjective;
more;más;2;comparison;
less;menos;2;comparison;
as…as;tan…como;2;comparison_structure;
than;que (comparación);2;comparison_word;
either;tampoco / cualquiera;2;connector;
neither;ninguno / tampoco;2;connector;
both;ambos;2;connector;
each;cada uno;2;determiner;
every;cada;2;determiner;
another;otro;2;determiner;
the same;el mismo;2;determiner;
the other;el otro;2;determiner;
something;algo;2;indefinite_pronoun;
someone;alguien;2;indefinite_pronoun;
somewhere;algún lugar;2;indefinite_pronoun;
anything;cualquier cosa / nada;2;indefinite_pronoun;
anyone;cualquiera / nadie;2;indefinite_pronoun;
nothing;nada;2;indefinite_pronoun;
nobody;nadie;2;indefinite_pronoun;
everything;todo;2;indefinite_pronoun;
everyone;todos;2;indefinite_pronoun;
before;antes;2;preposition_time;
after;después;2;preposition_time;
during;durante;2;preposition_time;
until;hasta;2;preposition_time;
since;desde;2;preposition_time;
above;encima de;2;preposition_place;
below;debajo de;2;preposition_place;
under;debajo;2;preposition_place;
over;sobre / encima;2;preposition_place;
between;entre;2;preposition_place;
among;entre;2;preposition_place;
inside;dentro;2;preposition_place;
outside;fuera;2;preposition_place;
near;cerca;2;preposition_place;
far;lejos;2;preposition_place;
around;alrededor;2;preposition_place;
across;a través de;2;preposition_movement;
along;a lo largo de;2;preposition_movement;
towards;hacia;2;preposition_movement;
away;lejos;2;adverb_place;
back;de vuelta;2;adverb_place;
up;arriba;2;adverb_place;
down;abajo;2;adverb_place;
again;otra vez;2;adverb;
once;una vez;2;adverb;
twice;dos veces;2;adverb;
usually;normalmente;2;adverb_frequency;
often;a menudo;2;adverb_frequency;
rarely;rara vez;2;adverb_frequency;
sometimes;a veces;2;adverb_frequency;
almost never;casi nunca;2;adverb_frequency;
right;derecha / correcto;2;adjective;
left;izquierda;2;adjective;
wrong;incorrecto;2;adjective;
possible;posible;2;adjective;
impossible;imposible;2;adjective;
important;importante;2;adjective;
necessary;necesario;2;adjective;
optional;opcional;2;adjective;
safe;seguro;2;adjective;
dangerous;peligroso;2;adjective;
simple;simple;2;adjective;
complex;complejo;2;adjective;
clear;claro;2;adjective;
confusing;confuso;2;adjective;
strong;fuerte;2;adjective;
weak;débil;2;adjective;
rich;rico;2;adjective;
poor;pobre;2;adjective;
early;temprano;2;adjective;
late;tarde;2;adjective;
first;primero;2;ordinal;
second;segundo;2;ordinal;
third;tercero;2;ordinal;
last;último;2;ordinal;
next;siguiente;2;ordinal;
one;uno;2;number;
two;dos;2;number;
three;tres;2;number;
four;cuatro;2;number;
five;cinco;2;number;
ten;diez;2;number;
hundred;cien;2;number;
thousand;mil;2;number;
half;mitad;2;fraction;
quarter;cuarto;2;fraction;
more or less;más o menos;2;approximation;
about;aproximadamente;2;approximation;
around;alrededor de;2;approximation;
at least;al menos;2;approximation;
at most;como máximo;2;approximation;
kind of;algo así;2;softener;
sort of;más o menos;2;softener;
maybe;quizás;2;softener;
I think;creo que;2;opinion_chunk;
I believe;creo;2;opinion_chunk;
in my opinion;en mi opinión;2;opinion_chunk;
it depends;depende;2;opinion_chunk;
for example;por ejemplo;2;connector;
for instance;por ejemplo;2;connector;
that is;es decir;2;connector;
in general;en general;2;connector;
in fact;de hecho;2;connector;
by the way;por cierto;2;connector;
by myself;por mí mismo;2;reflexive_expression;
yourself;tú mismo;2;reflexive_pronoun;
himself;él mismo;2;reflexive_pronoun;
herself;ella misma;2;reflexive_pronoun;
itself;por sí mismo;2;reflexive_pronoun;
ourselves;nosotros mismos;2;reflexive_pronoun;
themselves;ellos mismos;2;reflexive_pronoun;
make sense;tener sentido;2;common_expression;
no idea;ni idea;2;common_expression;
I agree;estoy de acuerdo;2;common_expression;
I disagree;no estoy de acuerdo;2;common_expression;
sounds good;suena bien;2;common_expression;
sounds bad;suena mal;2;common_expression;
it’s ok;está bien;2;common_expression;
it’s fine;todo bien;2;common_expression;
it’s up to you;depende de ti;2;common_expression;
what do you mean;qué quieres decir;2;common_expression;
what else;qué más;2;common_expression;
nothing else;nada más;2;common_expression;
just in case;por si acaso;2;common_expression;
as soon as;tan pronto como;2;time_structure;
as long as;siempre que;2;time_structure;
right away;de inmediato;2;time_expression;
from now on;de ahora en adelante;2;time_expression;
so far;hasta ahora;2;time_expression;
at the moment;en este momento;2;time_expression;
in the past;en el pasado;2;time_expression;
in the future;en el futuro;2;time_expression;
used to;solía;2;past_habit_structure;
would;solía (pasado);2;past_habit_structure;
was going to;iba a;2;past_future_structure;
have been;he estado;2;present_perfect;
has gone;ha ido;2;present_perfect;
have done;he hecho;2;present_perfect;
did;núcleo pasado simple;2;past_simple;
was;era / estaba;2;past_simple;
were;eran / estaban;2;past_simple;
will be;será / estará;2;future_simple;
will have;habrá tenido;2;future_perfect;
can’t;no poder;2;negative_modal;
mustn’t;no deber;2;negative_modal;
shouldn’t;no debería;2;negative_modal;
don’t;auxiliar negativo;2;auxiliary;
doesn’t;auxiliar negativo;2;auxiliary;
didn’t;auxiliar negativo pasado;2;auxiliary;
isn’t;no es / no está;2;auxiliary;
aren’t;no son / no están;2;auxiliary;
wasn’t;no era / no estaba;2;auxiliary;
weren’t;no eran / no estaban;2;auxiliary;
let’s;hagamos;2;suggestion;
why not;por qué no;2;suggestion;
how about;qué tal;2;suggestion;
what if;y si;2;suggestion;
sure;claro;2;agreement;
okay;ok;2;agreement;
fine;bien;2;agreement;
maybe later;quizás luego;2;soft_refusal;
not now;ahora no;2;soft_refusal;
I’m busy;estoy ocupado;2;soft_refusal;
I don’t know;no sé;2;basic_expression;
I don’t care;no me importa;2;basic_expression;
I don’t mind;no me molesta;2;basic_expression;
I hope;espero;2;basic_expression;
I guess;supongo;2;basic_expression;
I mean;quiero decir;2;discourse_marker;
you know;ya sabes;2;discourse_marker;
well;bueno;2;discourse_marker;
actually;en realidad;2;discourse_marker;
basically;básicamente;2;discourse_marker;
literally;literalmente;2;discourse_marker;
get;obtener / conseguir;2;verb;
get along;llevarse bien;2;phrasal_verb;
get by;arreglárselas;2;phrasal_verb;
get over;superar;2;phrasal_verb;
get used to;acostumbrarse a;2;phrasal_verb;
get rid of;deshacerse de;2;phrasal_verb;
get back to;volver a;2;phrasal_verb;
take;coger / tomar;2;verb;
take care;cuidarse;2;phrasal_verb;
take place;tener lugar;2;phrasal_verb;
take off;quitar / despegar;2;phrasal_verb;
take over;hacerse cargo;2;phrasal_verb;
make sure;asegurarse;2;phrasal_verb;
make sense;tener sentido;2;phrasal_verb;
make up;inventar / reconciliarse;2;phrasal_verb;
make it;lograrlo;2;phrasal_verb;
do well;hacerlo bien;2;phrasal_verb;
do badly;hacerlo mal;2;phrasal_verb;
set;establecer / colocar;2;verb;
set up;configurar / montar;2;phrasal_verb;
set off;salir / detonar;2;phrasal_verb;
keep;mantener;2;verb;
keep on;seguir;2;phrasal_verb;
keep up;mantener el ritmo;2;phrasal_verb;
keep in mind;tener en cuenta;2;phrasal_verb;
hold;sostener;2;verb;
hold on;esperar;2;phrasal_verb;
hold back;contener;2;phrasal_verb;
run;funcionar / correr;2;verb;
run out;quedarse sin;2;phrasal_verb;
run into;encontrarse con;2;phrasal_verb;
carry;llevar;2;cverb;
carry on;continuar;2;phrasal_verb;
deal with;tratar con;2;phrasal_verb;
figure out;averiguar;2;phrasal_verb;
point out;señalar;2;phrasal_verb;
find out;descubrir;2;phrasal_verb;
turn out;resultar;2;phrasal_verb;
bring up;sacar el tema;2;phrasal_verb;
come across;encontrarse con;2;phrasal_verb;
go through;pasar por;2;phrasal_verb;
cut down;reducir;2;phrasal_verb;
put off;posponer;2;phrasal_verb;
look forward to;esperar con ganas;2;phrasal_verb;
feel like;tener ganas;2;phrasal_verb;
be used to;estar acostumbrado a;2;structure;
be about to;estar a punto de;2;structure;
would rather;preferiría;2;structure;
had better;sería mejor;2;structure;
as if;como si;2;connector;
even though;aunque;2;connector;
unless;a menos que;2;connector;
while;mientras;2;connector;
whereas;mientras que;2;connector;
instead of;en lugar de;2;connector;
due to;debido a;2;connector;
according to;según;2;connector;
in order to;para;2;purpose_structure;
so that;para que;2;purpose_structure;
therefore;por lo tanto;2;connector;
however;sin embargo;2;connector;
otherwise;de lo contrario;2;connector;
meanwhile;mientras tanto;2;connector;
actually;en realidad;2;discourse_marker;
apparently;aparentemente;2;discourse_marker;
eventually;finalmente;2;discourse_marker;
basically;básicamente;2;discourse_marker;
honestly;honestamente;2;discourse_marker;
seriously;en serio;2;discourse_marker;
probably;probablemente;2;discourse_marker;
it seems;parece;2;opinion_structure;
it looks like;parece que;2;opinion_structure;
I suppose;supongo;2;opinion_structure;
I’m not sure;no estoy seguro;2;opinion_structure;
I’d say;yo diría;2;opinion_structure;
from my point of view;desde mi punto de vista;2;opinion_structure;
as far as I know;hasta donde sé;2;opinion_structure;
do you mind;te importa;2;polite_structure;
would you mind;le importaría;2;polite_structure;
could you;podrías;2;polite_structure;
would you;podrías / le gustaría;2;polite_structure;
is it okay;está bien si;2;polite_structure;
no worries;no hay problema;2;informal_expression;
fair enough;me parece bien;2;informal_expression;
that’s fine;está bien;2;informal_expression;
that works;funciona;2;informal_expression;
I see;entiendo;2;informal_expression;
makes sense;tiene sentido;2;informal_expression;
not really;no realmente;2;soft_disagreement;
I guess so;supongo que sí;2;soft_agreement;
I don’t think so;no lo creo;2;soft_disagreement;
maybe not;tal vez no;2;soft_disagreement;
it depends;depende;2;soft_answer;
more or less;más o menos;2;soft_answer;
kind of;algo así;2;soft_answer;
sort of;más o menos;2;soft_answer;
get together;reunirse;2;phrasal_verb;
catch up;ponerse al día;2;phrasal_verb;
hang out;pasar el rato;2;phrasal_verb;
show up;aparecer;2;phrasal_verb;
check out;revisar / echar un vistazo;2;phrasal_verb;
work out;funcionar / entrenar;2;phrasal_verb;
break down;averiarse;2;phrasal_verb;
break up;terminar (relación);2;phrasal_verb;
bring about;provocar;2;phrasal_verb;
call off;cancelar;2;phrasal_verb;
come up;aparecer / surgir;2;phrasal_verb;
end up;terminar;2;phrasal_verb;
fall apart;desmoronarse;2;phrasal_verb;
fill out;rellenar (formulario);2;phrasal_verb;
find out;descubrir;2;phrasal_verb;
give away;regalar / revelar;2;phrasal_verb;
go ahead;adelante;2;phrasal_verb;
grow up;crecer;2;phrasal_verb;
hand in;entregar;2;phrasal_verb;
let down;decepcionar;2;phrasal_verb;
pass out;desmayarse / repartir;2;phrasal_verb;
put away;guardar;2;phrasal_verb;
set aside;reservar / apartar;2;phrasal_verb;
sort out;resolver / organizar;2;phrasal_verb;
take care of;cuidar de;2;phrasal_verb;
turn down;rechazar / bajar;2;phrasal_verb;
turn up;aparecer / subir;2;phrasal_verb;
wipe out;eliminar;2;phrasal_verb;
in the long run;a largo plazo;2;idiom;
on the other hand;por otro lado;2;idiom;
at the end of the day;al final del día;2;idiom;
once in a while;de vez en cuando;2;idiom;
sooner or later;tarde o temprano;2;idiom;
by chance;por casualidad;2;idiom;
on purpose;a propósito;2;idiom;
in a hurry;con prisa;2;idiom;
out of place;fuera de lugar;2;idiom;
out of time;sin tiempo;2;idiom;
I’m used to;estoy acostumbrado a;2;structure;
I’d rather not;preferiría no;2;structure;
I don’t feel like;no tengo ganas;2;structure;
I’m not used to;no estoy acostumbrado a;2;structure;
I was wondering;me preguntaba;2;polite_structure;
would it be possible;sería posible;2;polite_structure;
do you happen to;casualmente;2;polite_structure;
as far as;en cuanto a;2;connector;
no matter;no importa;2;connector;
even if;aunque;2;connector;
whatever;lo que sea;2;indefinite;
whoever;quien sea;2;indefinite;
whenever;cuando sea;2;indefinite;
wherever;donde sea;2;indefinite;`